### ISSUE TITLE
TO - Error generating cdn.conf in postinstall

### ISSUE THREAD

**Issue by ezelkow1** [apache/incubator-trafficcontrol#1495]
Many have reported this error while attempting the postinstall:

```
===========/opt/traffic_ops/app/conf/cdn.conf===========
Generate a new secret? [yes]:
Generate a new secret?: yes
Number of secrets to keep? [1]:
Number of secrets to keep?: 1
Number of workers? [12]:
Number of workers?: 12
Traffic Ops url? [http://localhost:3000]:
Traffic Ops url?: http://localhost:3000
'"' expected, at character offset 4 (before "hypnotoad => {\n    ...") at /opt/traffic_ops/install/lib/InstallUtils.pm line 206.
```

**Comment by KevinMackenzie** [comment]
I did some investigating and after installing, but before the postinstall, the `/opt/traffic_ops/app/conf/cdn.conf` is not in the json format.  The `install/lib/GenerageCert.pm` script will attempt to create a new `cdn.conf` and overwrite the existing one, but it still saves it using `Data::Dumper` instead of `InstallUtils::writeJson`, so it ends up in the wrong format.
