### ISSUE TITLE
Traffic Portal server checks missing management interface column

### ISSUE THREAD

**Issue by dneuman64** [apache/incubator-trafficcontrol#2000]
In traffic ops, there is a column in the server checks page called MGMT for the management interface.  This column appears to be missing in Traffic Portal.

**Comment by mitchell852** [comment]
This is because in TP, the server checks (cache checks) table is not being dynamically created based on the data it has available.

https://github.com/apache/incubator-trafficcontrol/blob/master/traffic_portal/app/src/modules/private/cacheChecks/cacheChecks.tpl.html#L34

^^ Those columns are "hard-coded" for a lack of a better term. I wasn't aware they had to be dynamically created. Will need to rethink how this table is built.

**Comment by hbeatty** [comment]
+1 for a fix on this issue.
