### ISSUE TITLE
TO changelog data enhancement

### ISSUE THREAD

**Issue by ezelkow1** [apache/incubator-trafficcontrol#2099]
It would be useful if the changelogs reported the actual server name instead of the id, since there is not a 1 to 1 mapping thats easy to find within TP itself.

Also being able to see specific up/down states and more information than APICHANGE would be very useful in diagnosing problematic servers

**Comment by mitchell852** [comment]
I think the whole change log needs to be revisited in my opinion. It is not robust enough but yes, at the very least, the current messages need to be better. 

For example, instead of "updated server id: 4", you should at least see "updated server with fqdn: foo-bar.blah.com" or something like that....

this should probably be addressed with each endpoint that is rewritten in Go.

@dangogh @dewrich @rivasj
