### ISSUE TITLE
Profiles endpoint unordered

### ISSUE THREAD

**Issue by jhg03a** [apache/incubator-trafficcontrol#2274]
With the Golang rewrite, the profiles endpoint is no longer ordered by name.  This makes the dialogs such as in delivery services more difficult to navigate.

**Comment by rob05c** [comment]
Ordering in the database can be expensive, and the API has never guaranteed order. See https://github.com/apache/incubator-trafficcontrol/issues/2259

I'm -1 on sorting in the database; better to put the workload on clients/browsers, than the server.

If you need to order, most languages can easily sort. On the command line, `curl -Lvsk --cookie $mc 'https://localhost/api/1.2/profiles' | jq '.response | sort_by(.name)'`

**Comment by mitchell852** [comment]
@rob05c may be right but perl supported a default order when fetching a list of profiles so we probably need to support ordering on the server side. this will need a couple of things:

1. GET /api/version/profiles?orderby=name needs to be supported in golang
2. all the calls in TP need to be changed from profileService.getProfiles() to profileService.getProfiles({ orderby: 'name' }) <-- this tacks ?orderby=name on to the request

**Comment by rob05c** [comment]
Can the Portal not simply `profiles.sort(function(a, b){if(a.name < b.name) return -1; else return 1})` ?

**Comment by mitchell852** [comment]
probably but seems like a pretty common feature of an api, no? orderby, limit, page, etc...

plus orderby has already been implemented in perl and implemented on some of the golang endpoints so it seems like a feature that has already been advertised...

**Comment by rob05c** [comment]
Just because something is common doesn't make it good. And yes, we have it on existing endpoints. But IMO we should be reducing unnecessary server load, not increasing it.

In this particular case, Perl didn't "support" it, it was an incidental implementation. Right now, things like this aren't a big deal, because we have a very slow requests/second rate, due to changes being limited to operations. But as we move to Self Service, that's going to change, and load is going to start mattering more, as hundreds and even thousands of users are using Traffic Ops at once, and each user is changing configuration much more frequently.

When that happens, there's a big difference in the TO server having to process 1000 concurrent requests and do the extra work to sort all of them at the same time, versus having all 1000 users sort their data client-side in the browser.

Ordering one endpoint is small, but every decision we make like this affects the overall scalability of the application. We should make good decisions now, not putting unnecessary work on the server, so we don't have to do more work to refactor both the client and the server, when Self Service increases our load 1000x.

**Comment by mitchell852** [comment]
@rob05c - its weird imo to have some apis support orderby and others not support it in API 1.x. How about we revisit this conversation with API 2.x. In 2.x, if we determine this is the best course of action for performance reasons, we can deprecate any sorting (orderby).
