### ISSUE TITLE
[TC-544] TR should de-dupe Reponse Headers when sending a Steering response.

### ISSUE THREAD

**Issue by limited** [apache/incubator-trafficcontrol#986]
<p>If you have a steering delivery service configured and the subordinate delivery services have the same Traffic Router Response Headers defined, you will get multiple Headers in your response.  <br/>
For example if you set CORS header on each of the subordinate DSs (e.g. Access-Control-Allow-Origin: *), you will end up with 3 CORS headers in your response.<br/>
This could cause an issue with some clients which will try to chain the headers together  (e.g. Access-Control-Allow-Origin: <b>,</b>,*).</p>

Author: David Neuman
JIRA Link: <a href="https://issues.apache.org/jira/browse/TC-544">https://issues.apache.org/jira/browse/TC-544</a>

**Comment by dneuman64** [comment]
It has been reported that the latest Chrome browser throws an error due to this issue.  Making this a major instead of a minor, we should think about fixing this in the next release.

**Comment by dneuman64** [comment]
We should HTTPRouteResult to have a reference to the steering DS. Use that reference to build the response headers for the multi-response response.
If a steering DS has headers defined, use those otherwise we either return nothing which forces the user to add headers to the steering DS.

**Comment by rob05c** [comment]
CDN-860 Release Note:

As part of 2.2 Traffic Ops upgrade, migration 20180130000000_update_client_steering_headers.sql is run in order to resolve an issue involving duplicating response headers. The migration updates client steering delivery services with the "Additional Traffic Router Response Headers" field of the target delivery service, if it exists. In the case there are multiple target delivery services with conflicting response headers, the updated response header of the client steering delivery service is nondeterministic, but this should not ever be the case. The target delivery services will remain unchanged.

**Comment by rivasj** [comment]
Name of the migration file updated to: 20180201000000_update_client_steering_headers.sql
